set -g pane-border-status top
setw -g mode-keys vi
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"


# --- Plugin manager initialization ---
set -g @plugin 'tmux-plugins/tpm'


# --- Plugins you want to install ---
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "https://gitlab.com/motaz-shokry/gruvbox-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'


# --- Load TPM ---
run '~/.tmux/plugins/tpm/tpm'


# Copy to clipboard oscyank
set -s set-clipboard on
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel


# Rebind prefix
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# Split panes
bind | split-window -h
bind - split-window -v


# Navigate panes with Vim keys jkl;
bind j select-pane -L
bind k select-pane -D
bind l select-pane -U
bind \; select-pane -R

# Theme gruvbox
set -g @gruvbox-tmux_theme "medium"
set -g @gruvbox-tmux_transparent 1
set -g @gruvbox-tmux_window_id_style hsquare
